### Numpy

In [1]:
# NumPy array (ndarray)
#    Fixed size
#    Homogenous
#    Can be reshaped
#    Elements have specialized, restricted data types
#    Have masking
#    Fancy index
# The array type is ndarray (n dimensional array)

# Rows are axis 0
# Columns are axis 1

In [2]:
import numpy as np

In [3]:
l = list(range(1, 6))
l

[1, 2, 3, 4, 5]

In [4]:
a = np.array(l)
a, type(a)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [5]:
a.dtype

dtype('int64')

In [6]:
a1 = np.array((.1, 2, 3, 4))
a1, a1.dtype

(array([0.1, 2. , 3. , 4. ]), dtype('float64'))

In [7]:
b = np.array([1, 2, 3], dtype=np.int8)

In [8]:
b, b.shape, b.size

(array([1, 2, 3], dtype=int8), (3,), 3)

In [9]:
lm = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [10]:
m = np.array(lm)

In [11]:
m

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
m.shape, m.size

((3, 3), 9)

### Arrays from scratch

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((3,5), dtype=np.int8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [15]:
np.ones((2,4), dtype=np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [16]:
np.full((5,4), 3.14, dtype=np.float32)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]], dtype=float32)

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [19]:
np.arange(3, 40, 3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [20]:
np.linspace(2, 50, num=10)

array([ 2.        ,  7.33333333, 12.66666667, 18.        , 23.33333333,
       28.66666667, 34.        , 39.33333333, 44.66666667, 50.        ])

In [21]:
np.random.random((4,3))

array([[0.00802219, 0.30658874, 0.57688711],
       [0.499487  , 0.34228766, 0.63751944],
       [0.28141729, 0.55315217, 0.95697281],
       [0.56040123, 0.23665712, 0.39017143]])

In [22]:
np.random.seed(3)
np.random.random((4,3))

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322]])

In [23]:
np.random.seed(3)
np.random.random((4,3))

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322]])

In [24]:
np.random.randint(3, 79, 200)

array([29, 25, 69,  5, 66, 63,  4, 54, 72, 32, 27, 65, 10, 46, 36, 51, 40,
       23, 52, 24, 31, 57,  3, 67, 21, 66, 40, 59, 59, 74, 40, 49, 36,  4,
       77, 19, 35, 19, 21, 78, 58, 16, 40, 33, 51, 64, 36, 55,  5, 31, 39,
       47, 51, 62, 77, 57, 24, 59, 42, 32, 35, 51, 12, 36, 63, 58, 14, 13,
       71, 47, 47, 22, 19, 42, 53, 68, 38, 48, 55,  4, 21, 66,  5, 23, 65,
       25, 10, 60, 46, 35, 63, 19, 30, 56, 11, 23, 11, 27, 22, 12, 29, 53,
       63,  8, 12, 35, 16, 47, 74, 39, 45, 75, 29, 27, 23, 65, 47, 33, 20,
       35, 56, 42, 63, 35, 36, 54, 14, 20, 54, 74, 16, 71, 66, 44, 16, 63,
       50, 39, 58, 59, 73, 15, 31, 13, 14, 38, 52, 75, 37, 14, 62,  7,  3,
       59, 48, 74, 24, 37, 32, 45, 10, 33, 78, 42, 60, 52, 47, 24, 44, 74,
       37, 18, 25, 48, 39, 43, 55, 12, 22, 72, 57, 15, 29, 38, 27, 55, 46,
       26, 53, 21, 67, 74, 56, 35, 29,  6, 40, 24, 26, 21])

In [25]:
np.random.randint(11,71,(5,3))

array([[45, 39, 17],
       [17, 30, 24],
       [65, 50, 56],
       [50, 11, 23],
       [51, 68, 15]])

### Reshaping Arrays

In [26]:
m = np.arange(12)
m, m.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [27]:
m1 = m.reshape(3, 4)
m1, m1.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [28]:
m2 = m1.reshape(2, 6)
m2, m2.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [29]:
m3 = m2.reshape(12,)
m3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
m[0] = 100

In [31]:
m, m1, m2

(array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11]),
 array([[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]]),
 array([[100,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11]]))

In [32]:
m1[1][2] = 60

In [33]:
m

array([100,   1,   2,   3,   4,   5,  60,   7,   8,   9,  10,  11])

In [34]:
m4 = m.reshape(4, 3).copy()

In [35]:
m4[0][0] = -1

In [36]:
m4, m

(array([[-1,  1,  2],
        [ 3,  4,  5],
        [60,  7,  8],
        [ 9, 10, 11]]),
 array([100,   1,   2,   3,   4,   5,  60,   7,   8,   9,  10,  11]))

### Stacking Arrays

In [37]:
a1 = np.arange(6,11)
a1

array([ 6,  7,  8,  9, 10])

In [38]:
a2 = np.arange(1, 11).reshape(2, 5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
v1 = np.vstack((a1, a2))
v1

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
a1 = np.linspace(1, 5, 6).reshape(3, 2)
a1

array([[1. , 1.8],
       [2.6, 3.4],
       [4.2, 5. ]])

In [41]:
a2 = np.random.randint(1, 10 ,6).reshape(3, 2)
a2

array([[6, 5],
       [6, 1],
       [4, 6]])

In [42]:
h1 = np.hstack((a1, a2))
h1

array([[1. , 1.8, 6. , 5. ],
       [2.6, 3.4, 6. , 1. ],
       [4.2, 5. , 4. , 6. ]])

### Indexing

In [44]:
ae = np.eye(3)
ae

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
ae[1,2] = 200
ae

array([[  1.,   0.,   0.],
       [  0.,   1., 200.],
       [  0.,   0.,   1.]])

In [46]:
ae[(1, 2)] = 201
ae

array([[  1.,   0.,   0.],
       [  0.,   1., 201.],
       [  0.,   0.,   1.]])

In [47]:
ae[1,2] = 202
ae

array([[  1.,   0.,   0.],
       [  0.,   1., 202.],
       [  0.,   0.,   1.]])

In [48]:
ae[1]

array([  0.,   1., 202.])

### Slicing

In [49]:
ar = np.arange(1,7)
ar

array([1, 2, 3, 4, 5, 6])

In [51]:
ar2 = ar[:3]
ar2

array([1, 2, 3])

In [53]:
# The arrarys are linked, differente from list.
ar2[0] = 100
ar2 ,ar

(array([100,   2,   3]), array([100,   2,   3,   4,   5,   6]))

In [55]:
ar = np.arange(1,26).reshape(5, 5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
# The first parameter is index 0 and the second is index 1 (column).
ar[:2, :2]

array([[1, 2],
       [6, 7]])

In [57]:
ar[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [58]:
ar[::2, ::2] = 100
ar

array([[100,   2, 100,   4, 100],
       [  6,   7,   8,   9,  10],
       [100,  12, 100,  14, 100],
       [ 16,  17,  18,  19,  20],
       [100,  22, 100,  24, 100]])

In [59]:
ar = np.arange(1,26).reshape(5, 5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
ar[2, 1::2]

array([12, 14])

In [62]:
ar = np.arange(1,7)
ar

array([1, 2, 3, 4, 5, 6])

In [64]:
ar[:3] = np.array([100, 200, 300])
ar

array([100, 200, 300,   4,   5,   6])

In [67]:
# Can use list too.
ar[:3] = [400, 500, 600]
ar

array([400, 500, 600,   4,   5,   6])

In [65]:
# Not work, must have the same size.
ar[:3] = np.array([100, 200, 300, 400])

ValueError: could not broadcast input array from shape (4,) into shape (3,)

In [68]:
ar = np.arange(9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
ar[::2, ::2]

array([[0, 2],
       [6, 8]])

In [70]:
ar[::2, ::2] = [[100, 200], [600, 800]]
ar

array([[100,   1, 200],
       [  3,   4,   5],
       [600,   7, 800]])

In [71]:
# Using broadcasting with scalar value.
ar[::2, ::2] = 700
ar

array([[700,   1, 700],
       [  3,   4,   5],
       [700,   7, 700]])