### Numpy

In [18]:
# NumPy array (ndarray)
#    Fixed size
#    Homogenous
#    Can be reshaped
#    Elements have specialized, restricted data types
#    Have masking
#    Fancy index
# The array type is ndarray (n dimensional array)

# Rows are axis 0
# Columns are axis 1

In [2]:
import numpy as np

In [6]:
l = list(range(1, 6))
l

[1, 2, 3, 4, 5]

In [9]:
a = np.array(l)
a, type(a)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [16]:
a.dtype

dtype('int64')

In [22]:
a1 = np.array((.1, 2, 3, 4))
a1, a1.dtype

(array([0.1, 2. , 3. , 4. ]), dtype('float64'))

In [13]:
b = np.array([1, 2, 3], dtype=np.int8)

In [32]:
b, b.shape, b.size

(array([1, 2, 3], dtype=int8), (3,), 3)

In [27]:
lm = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [28]:
m = np.array(lm)

In [29]:
m

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [33]:
m.shape, m.size

((3, 3), 9)

### Arrays from scratch

In [34]:
np.zeros(4)

array([0., 0., 0., 0.])

In [37]:
np.zeros((3,5), dtype=np.int8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [39]:
np.ones((2,4), dtype=np.float32)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [40]:
np.full((5,4), 3.14, dtype=np.float32)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]], dtype=float32)

In [41]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [47]:
np.arange(3, 40, 3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [49]:
np.linspace(2, 50, num=10)

array([ 2.        ,  7.33333333, 12.66666667, 18.        , 23.33333333,
       28.66666667, 34.        , 39.33333333, 44.66666667, 50.        ])

In [54]:
np.random.random((4,3))

array([[0.91121409, 0.129334  , 0.45827   ],
       [0.29393053, 0.54094999, 0.68388469],
       [0.90885554, 0.35188126, 0.89989917],
       [0.52821953, 0.81323849, 0.45838855]])

In [68]:
np.random.seed(3)
np.random.random((4,3))

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322]])

In [69]:
np.random.seed(3)
np.random.random((4,3))

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322]])

In [70]:
np.random.randint(3, 79, 200)

array([29, 25, 69,  5, 66, 63,  4, 54, 72, 32, 27, 65, 10, 46, 36, 51, 40,
       23, 52, 24, 31, 57,  3, 67, 21, 66, 40, 59, 59, 74, 40, 49, 36,  4,
       77, 19, 35, 19, 21, 78, 58, 16, 40, 33, 51, 64, 36, 55,  5, 31, 39,
       47, 51, 62, 77, 57, 24, 59, 42, 32, 35, 51, 12, 36, 63, 58, 14, 13,
       71, 47, 47, 22, 19, 42, 53, 68, 38, 48, 55,  4, 21, 66,  5, 23, 65,
       25, 10, 60, 46, 35, 63, 19, 30, 56, 11, 23, 11, 27, 22, 12, 29, 53,
       63,  8, 12, 35, 16, 47, 74, 39, 45, 75, 29, 27, 23, 65, 47, 33, 20,
       35, 56, 42, 63, 35, 36, 54, 14, 20, 54, 74, 16, 71, 66, 44, 16, 63,
       50, 39, 58, 59, 73, 15, 31, 13, 14, 38, 52, 75, 37, 14, 62,  7,  3,
       59, 48, 74, 24, 37, 32, 45, 10, 33, 78, 42, 60, 52, 47, 24, 44, 74,
       37, 18, 25, 48, 39, 43, 55, 12, 22, 72, 57, 15, 29, 38, 27, 55, 46,
       26, 53, 21, 67, 74, 56, 35, 29,  6, 40, 24, 26, 21])

In [71]:
np.random.randint(11,71,(5,3))

array([[45, 39, 17],
       [17, 30, 24],
       [65, 50, 56],
       [50, 11, 23],
       [51, 68, 15]])

### Reshaping Arrays

In [79]:
m = np.arange(12)
m, m.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [80]:
m1 = m.reshape(3, 4)
m1, m1.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [82]:
m2 = m1.reshape(2, 6)
m2, m2.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [83]:
m3 = m2.reshape(12,)
m3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
m[0] = 100

In [86]:
m, m1, m2

(array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11]),
 array([[100,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]]),
 array([[100,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11]]))

In [87]:
m1[1][2] = 60

In [88]:
m

array([100,   1,   2,   3,   4,   5,  60,   7,   8,   9,  10,  11])

In [89]:
m4 = m.reshape(4, 3).copy()

In [90]:
m4[0][0] = -1

In [91]:
m4, m

(array([[-1,  1,  2],
        [ 3,  4,  5],
        [60,  7,  8],
        [ 9, 10, 11]]),
 array([100,   1,   2,   3,   4,   5,  60,   7,   8,   9,  10,  11]))